version: '3.3'

services:
  gateway:
    image: ocelot-gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    container_name: ocelot-gateway
    ports:
      - "0.0.0.0:7777:7777"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7777
    depends_on:
      - sales-api
    networks:
      - evaluation-network

  sales-api:
    image: sales-api
    build:
      context: .
      dockerfile: SalesApi/Dockerfile
    container_name: sales-api
    depends_on:
      - mongo
    ports:
      - "8090:8090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SalesApiDb=mongodb://mongo:27017/SalesApiDb
    networks:
      - evaluation-network
    tty: true

  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: SalesApiDb
    ports:
      - "27017:27017"
    networks:
      - evaluation-network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local

networks:
  evaluation-network:
    external: true
